print("You are standing faced with the decission of your life, a trolly is high speeding towards Five people tied down on the track, luckly for your a level is located in front of you, this lever will divert the tram to the other track, But unfortunatly there is another victim tied on the track.")
print("---------------------------------------------------------------------------------------------------------------------------")
user_choice = input("Will you pull the lever to sacrafice the life of someone to save five others, or do nothing and stay out of the situation. ('yes'or 'no') ")

print1 = print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX(You do 'yes' as in do nothing and stay out of the situation.) You decide to do absolutely nothing, YOU MONSTER!!! You really think leaving five people to die was the right thing to do, this outcome will very much negitively effect your life future... -------------------------------------------------------------------------------------------------------------------------------------------------------------------- YOUR LIFE IS AN ABSOLUTE TRAIN WRECK. First off you die at the age 30 with nothing special going on, you work a basic 9-5, have no friends, never got anywhere, parents disowned you and you die in a tragic train crash with 150 other people, so yes a train wreck.")

print2 = print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX(You do 'yes' as in do nothing and stay out of the situation.) You decide to do absolutely nothing, YOU MONSTER!!! You really think leaving five people to die was the right thing to do, this outcome will very much negitively effect your life future... -------------------------------------------------------------------------------------------------------------------------------------------------------------------- On your way home after the drama, you see a small racoon, turns out it's feral, (baserk) you enter a hand to hand combat with the racoon, you get a couple good punches in before it lands its fatal blower, weakening your ankle and you trip and fall into the nearby sewer, to live in there for the rest of your life with rabies.")

print3 = print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX(you do 'no' as in not do nothing and pull the lever. You decide to pull the level, YOU MONSTER!!! You really think your a hero for killing somone who could have lived, so what if it saved five people now you are going to live in guilt, this outcome will very much negitively effect your life future... -------------------------------------------------------------------------------------------------------------------------------------------------------------------- Five days later you hear a knock on the door, you open it and no one is there, you hear a slight rustle and before you know it a swat team smashes through the ceiling, you are arrested for murder, and set on trial, you get given the death penalty, bye bye life.")

if user_choice == "yes" or "Yes" or "YES" or "yES":
    print(print1) or print(print2) 